apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: user-reader
  namespace: eshop-config
spec:
  displayName: User Reader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Team
      - User
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: cluster-reader
  namespace: eshop-config
spec:
  displayName: Cluster Reader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Cluster
      - Organization
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: Role
metadata:
  name: tenant-reader
  namespace: eshop-config
spec:
  displayName: Tenant Reader
  rules:
  - permissions:
    - READ
    types:
    - apiGroup: api.tsb.tetrate.io/v2
      kinds:
      - Tenant
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  name: tetrate-org
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate
spec:
  allow:
  - role: rbac/registryreader
    subjects:
    - team: organizations/tetrate/teams/everyone
  - role: rbac/user-reader
    subjects:
    - team: organizations/tetrate/teams/everyone
  - role: rbac/cluster-reader
    subjects:
    - team: organizations/tetrate/teams/everyone
  - role: rbac/admin
    subjects:
    - serviceAccount: teamsync-job
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  name: eshop-tenant
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop
spec:
  allow:
  - role: rbac/admin
    subjects:
    - serviceAccount: admin
  - role: rbac/creator
    subjects:
    - user: organizations/tetrate/users/${tenant_owner}
  - role: rbac/tenant-reader
    subjects:
    - team: organizations/tetrate/teams/eshop-team
    - team: organizations/tetrate/teams/payments-team
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  name: payments-workspace
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/payments
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${tenant_owner}
  - role: rbac/creator
    subjects:
    - team: organizations/tetrate/teams/payments-team
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  name: eshop-workspace
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/eshop
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${tenant_owner}
  - role: rbac/creator
    subjects:
    - team: organizations/tetrate/teams/eshop-team
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  name: payments-gateways
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/payments/gatewaygroups/payments-gateways
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${payments_owner}
---
apiVersion: rbac.tsb.tetrate.io/v2
kind: AccessBindings
metadata:
  name: eshop-gateways
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/fqn: organizations/tetrate/tenants/eshop/workspaces/eshop/gatewaygroups/eshop-gateways
spec:
  allow:
  - role: rbac/admin
    subjects:
    - user: organizations/tetrate/users/${eshop_owner}
