apiVersion: tsb.tetrate.io/v2
kind: Team
metadata:
  name: everyone
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  members:
  - organizations/tetrate/users/${tenant_owner}
  - organizations/tetrate/users/${eshop_owner}
  - organizations/tetrate/users/${payments_owner}
---
apiVersion: tsb.tetrate.io/v2
kind: Team
metadata:
  name: eshop-team
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  members:
  - organizations/tetrate/users/${eshop_owner}
---
apiVersion: tsb.tetrate.io/v2
kind: Team
metadata:
  name: payments-team
  namespace: eshop-config
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  members:
  - organizations/tetrate/users/${payments_owner}
