---
apiVersion: tsb.tetrate.io/v2
kind: Workspace
metadata:
  name: gitops-grpc-ws
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
spec:
  namespaceSelector:
    names:
      - "*/gitops-grpc"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: gitops-grpc-gg
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-grpc-ws
spec:
  namespaceSelector:
    names:
      - "*/gitops-grpc"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  name: gitops-grpc-tg
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-grpc-ws
spec:
  namespaceSelector:
    names:
      - "*/gitops-grpc"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  name: gitops-grpc-sg
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-grpc-ws
spec:
  namespaceSelector:
    names:
      - "*/gitops-grpc"
  configMode: BRIDGED
