---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-opa-s2s-httpbin
  namespace: argocd
spec:
  destination:
    namespace: gitops-opa-s2s-httpbin
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/opa-s2s-httpbin
    repoURL: https://github.com/smarunich/tetrate-service-bridge-sandbox.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
