---
piVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-bookinfo
  namespace: gitops-bookinfo
spec:
  destination:
    namespace: gitops-bookinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gitops/bookinfo
    repoURL: https://github.com/smarunich/azure-tsb-tf-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
